Added MostEventfulDayFact fact
AtrisFlax/ItHappened pull request #108
Opened 2020-10-20 20:49 UTC by AtrisFlax

2020-10-20 22:10 UTC, Romarub commented on ItHappened.UnitTests/StatisticsCalculatorsTests/MostEventfulDayCalculatorTest.cs
> +
Не вижу, чтобы функция применимости где-то тестилась.
1.Допустим есть только дни, в которые произошло не более одного события - функция применимости такой случай не пропускает
2.Допустим дней с макс кол-вом событий несколько. Показать, что выбирается самый поздний из них.

2020-10-20 22:10 UTC, Romarub requested changes
тесты

2020-10-21 09:37 UTC, AtrisFlax commented on ItHappened.UnitTests/StatisticsCalculatorsTests/MostEventfulDayCalculatorTest.cs
> +
Поменял название класса на  
MostEventfulAreTwoDaysWithSameEventfulnessChoseMoreLateDay_CalculateSuccess 
Он соотвествует этому сценарию 

> 2.Допустим дней с макс кол-вом событий несколько. Показать, что выбирается самый поздний из них.

2020-10-21 09:44 UTC, AtrisFlax commented on ItHappened.UnitTests/StatisticsCalculatorsTests/MostEventfulDayCalculatorTest.cs
> +
> Не более одного события - функция применимости такой случай не пропускает

Следующие тесты учитывают сценарий :

- TrackerHaveOneEvent_CalculateFailure
- TrackerHaveZeroEvent_CalculateFailure

2020-10-21 10:01 UTC, Romarub approved these changes

2020-10-21 10:02 UTC, merged