Elanskiy/most frequent event
AtrisFlax/ItHappened pull request #68
Opened 2020-10-17 19:51 UTC by seriousnik

2020-10-18 12:34 UTC, Romarub requested changes
рекомендую привести структуру классов к принятой архитектуре, перенести фомирование факта в калькулятор, упростить тесты

2020-10-18 12:34 UTC, Romarub commented on ItHappened.Domain/Statistics/Facts/ForMultipleTrackers/MostFrequentEventFact.cs
>          }
Мы обговаривали, что все поля формируются в калькуляторах, а объект факта просто хранит в себе все данные, которые он получает от калькулятора через конструктор

2020-10-18 12:34 UTC, Romarub commented on ItHappened.Domain/Statistics/Facts/ForMultipleTrackers/MostFrequentEventFact.cs
>  }
Еще обговаривали по структуре класса, чтобы у всех был один стиль:
Класс формируется так:
поля
свойства
конструкторы
методы

2020-10-18 12:34 UTC, Romarub commented on ItHappened.UnitTests/StatisticsCalculatorsTests/MostFrequentEventCalculatorTest.cs
> +        public void CreateTwoEventTrackersWithHeadacheAndToothacheEvents_GetMostFrequentEventFact_CheckAllProperties()
по названию и по объему теста видно, что он проверяет сразу много всего. Не понятно где области arrange, act, assert. 
Поддерживать его будет сложно, т.к. нужно вникнуть в кучу кода. Я бы разделил на несколько небольших тестов

2020-10-18 12:34 UTC, Romarub commented on ItHappened.Domain/Statistics/Facts/ForSingleTracker/SpecificDayTimeEventFact.cs
>      }
Этот файл не принадлежит к этому pull request'y по смыслу

2020-10-18 16:25 UTC, merged

2020-10-19 20:40 UTC, seriousnik commented on ItHappened.Domain/Statistics/Facts/ForMultipleTrackers/MostFrequentEventFact.cs
>          }
такое себе, ну черт с ним

2020-10-19 20:41 UTC, seriousnik commented on ItHappened.Domain/Statistics/Facts/ForMultipleTrackers/MostFrequentEventFact.cs
>  }
да, это по гайдлайну МС, но мне нравится, как Виталик предложил делать. Но ок, раз в команде так решили, спорить не буду. Мне непринципиально

2020-10-19 20:42 UTC, seriousnik commented on ItHappened.UnitTests/StatisticsCalculatorsTests/MostFrequentEventCalculatorTest.cs
> +        public void CreateTwoEventTrackersWithHeadacheAndToothacheEvents_GetMostFrequentEventFact_CheckAllProperties()
но вот тут я точно поспорю, потому что это один тест на весь факт. Мне просто нужно добавить еще один или два. Никто не должен вникать в тесты.

2020-10-19 20:43 UTC, seriousnik commented on ItHappened.Domain/Statistics/Facts/ForSingleTracker/SpecificDayTimeEventFact.cs
>      }
так вышло)